Separate meca path with reviews
elifesciences/data-hub-api pull request #162
Opened 2024-04-25 13:33 UTC by de-code

This is the draft DocMap change that we discussed during the meeting.

Open questions:

- Is the meca path going to be the same
- What should the exact meca path be?

2024-04-26 10:11 UTC, scottaubrey approved these changes

2024-04-26 12:17 UTC, fred-atherden approved these changes

2024-05-20 17:09 UTC, de-code commented
This now has become an output of `b1` (instead of `b2`). Would be good to re-review.

2024-05-24 11:28 UTC, scottaubrey requested changes
Hey @de-code 

I've had a relook at this and I think I missed the first time that we have an incorrect typing. I've explained as a comment on the type line, but I think we should change the additional action:
```
{
  "type": "preprint",
  "identifier": "80984",
  "doi": "10.7554/eLife.80984.1",
  "versionIdentifier": "1",
  "content": [
    {
        "type": "computer-file",
        "url": "s3://prod-elife-epp-meca/reviewed-preprints/86284-v1-meca.zip"
    }
  ]
}
```
`license` and other properties are optional.

2024-05-24 11:28 UTC, scottaubrey commented on data/docmaps/regression_test/docmap_by_manuscript_id/80984.json
> +                        "type": "computer-file",
As per the [docmap framework documentation](https://docmaps.knowledgefutures.org/pub/sgkf1pqa#convention-summary), the output should be an [`expression`](https://sparontologies.github.io/fabio/current/fabio.html#d4e3239), but [`computer-file`](https://sparontologies.github.io/fabio/current/fabio.html#d4e2608) is a manifestation.

So output should recreate the values from the [draft RPP Thing](https://github.com/elifesciences/data-hub-api/pull/162/files#diff-71bfaaf7453740566a15d1f8cc5640f283ec98f62f187dbed739f1b197bcc341R24-R30), and attach `content` to that duplicated item.

2024-05-28 10:32 UTC, de-code commented
> I've had a relook at this and I think I missed the first time that we have an incorrect typing. I've explained as a comment on the type line, but I think we should change the additional action:

This has changed when it moved from `b2` to `b1`. I have updated it now as per your suggestion.

2024-05-28 20:25 UTC, scottaubrey approved these changes

2024-06-14 11:31 UTC, HazalCiplak commented
This changes are deployed to the staging and example DocMaps with MECA path updated for regression test in [this related PR](https://github.com/elifesciences/data-hub-api/pull/184).
I am closing this PR. (No need to merge)

2024-06-14 11:31 UTC, closed without merging